### ISSUE TITLE
FAR aerodynamic failures

### ISSUE THREAD

**Issue by bssthu** [ferram4/BetterBuoyancy#3]
It's a nice mod, but FAR's aerodynamic failures seem to cause explosion when trying water landing with BetterBuoyancy.
I was using FAR v0.14.6 and BetterBuoyancy v1.0.

If it's intend to be like this, I think it would be better to hide the explosion effect.

![f](https://cloud.githubusercontent.com/assets/7445439/5613369/41bcbecc-951e-11e4-8ca1-da6eb62edaed.gif)

(not sure FAR or BB caused the issue..)

**Comment by ferram4** [comment]
Intended behavior, explosions are only there because it's more ~Kerbal~.  Turn them off in the FAR settings if it bothers you.
