### ISSUE TITLE
So, I tried using structural fuselages as floats and that did not work... at all

### ISSUE THREAD

**Issue by benthor** [ferram4/BetterBuoyancy#4]
I made a small float plane (about 4 tons) and figured that 6 structural fuselages would be enough to provide enough buoyancy to allow me to use them as floats.

What followed I detailed in [this imgur album](https://imgur.com/a/Qbt7B).

Care to enlighten me where I might have gone wrong?

**Comment by ferram4** [comment]
It's obviously denser than the water, or you have an installation error.  If it's the former, it's not a bug.  If it's the latter, it's not on my end.
